server:
  port: 8081

spring:
  application:
    name: inference-gateway
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  mvc:
    async:
      request-timeout: 45s
  task:
    execution:
      mode: force

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,kafka
      logging:
        slow-indicator-threshold: 1s
